### ISSUE TITLE
Uncaught error on line 44

### ISSUE THREAD

**Issue by ChoonKwang** [leomoon-studios/json-form-generator#1]
Hi i ran your example and it actually got this error. I am using php7.4. Not sure what is the issue..

Notice: Array to string conversion in D:\xampp\htdocs\fg\form.class.php on line 44

Notice: Undefined property: Form::$Array in D:\xampp\htdocs\fg\form.class.php on line 44

Notice: Trying to access array offset on value of type null in D:\xampp\htdocs\fg\form.class.php on line 44

Fatal error: Uncaught Error: Function name must be a string in D:\xampp\htdocs\fg\form.class.php:44 Stack trace: #0 D:\xampp\htdocs\fg\form.class.php(197): Form->parse(Array) #1 D:\xampp\htdocs\fg\form.class.php(207): Form->render() #2 D:\xampp\htdocs\fg\example.php(19): Form->show() #3 {main} thrown in D:\xampp\htdocs\fg\form.class.php on line 44

**Comment by arash817** [comment]
Fixed. the problem was about function name string conversion in PHP7. I tested the example with PHP version 7.2.29 and it works fine.
Thanks for the test and report this bug.
